global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:4000']

  - job_name: 'media-service'
    static_configs:
      - targets: ['media-service:6000']

  - job_name: 'signaling-service'
    static_configs:
      - targets: ['signaling-service:5000']
